services:

  postgres_srvc:
    image: postgres:17.5-alpine
    container_name: user_manager_db_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_manager_db
#    container's port assigned to the host's port
    ports:
      - "5432:5432"