spring:
  application:
    name: user.init
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations: schema.sql
      mode: always

data:
  users:
  - fname: John
    lname: Doe
    birthDate: 1995-01-01
  - fname: Anne
    lname: Smith
    birthDate: 1985-03-22
  - fname: Harry
    lname: Lewis
    birthDate: 1990-06-21
  - fname: Peter
    lname: Another
    birthDate: 2002-10-08