spring:
  application:
    name: user.init
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        ddl-auto: auto
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

data:
  users:
  - fname: John
    lname: Doe
    birthDate: 1995-01-01
  - fname: hAnne
    lname: Smith
    birthDate: 1985-03-22