set search_path to postgres, public;

DROP TABLE IF EXISTS user_entity;
CREATE TABLE user_entity (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fname VARCHAR(255),
  lname VARCHAR(255),
  birth_date VARCHAR(255)
);